### PR TITLE
Docker Support

### LINKED ISSUE #7: Docker Support
I'm going to make Dockerfile to run map on my network :smile:

### PR DESCRIPTION
**Pull request by cwchristerw**
CWINFO (@cwinfo)
-------------------------
Updates graph every minute.

Future improvements: 
Considering changing update time to every second minute, but it takes longer to start serving map after update. (possible to add line that updateGraph in Dockerfile)
Change image from debian:stretch to alpine but need more testing

Fixes #7

### CODE REVIEW

**Comment by cwchristerw** [comment]
Changes needed to web.py, it should possible to change host and port with environment variable
if name == 'main':
app.run(host='localhost', port=3000)

**Comment by cwchristerw** [comment]
Dont merge yet :smile: Will try 5 minute update and changed a bit entrypoint.sh to cd /src/yggdrasil-map/web/ && python updateGraph.py at start of the container in that way, container will start to serve map immediately instead of waiting 5 minute

**Comment by Arceliar** [comment]
The network gets scanned for `y.yakamo.org:3000/current` once every ~20 minutes, if you're using that as input, so there probably wouldn't have been much advantage in updating every minute. Something in the 5-10 minute range seems reasonable, just new nodes show up within something like 25-30 minutes.

**Comment by Arceliar** [comment]
I added options to `web.py` to take `--host` and `--port` arguments, which should hopefully help with your container config. Feel free to rename `--host` to `--ip` or something if you like that better. I'll leave the PR open for now, in case there was anything you wanted to change now that those args are available. Let me know if/when you're ready to merge (or request a PR review, that should get my attention).

**Comment by cwchristerw** [comment]
I think all things are now fine and also map is working with these :smile:

**Pull request merged**
